
local LevelConfigData = require("data.slotsdata.LevelConfigData")
local LevelBombPurrglarConfig = class("LevelBombPurrglarConfig", LevelConfigData)

--[[
    一些常量
]]
--背景音乐
LevelBombPurrglarConfig.Music_enterLevel = "BombPurrglarSounds/music_BombPurrglar_enter.mp3"
LevelBombPurrglarConfig.Music_bonusGame = "BombPurrglarSounds/music_BombPurrglar_bonusGame.mp3"
--音效
LevelBombPurrglarConfig.Sound_WinCoin_Base = "BombPurrglarSounds/sound_BombPurrglar_baseWin_%d.mp3"

LevelBombPurrglarConfig.Sound_Collect_flyStart = "BombPurrglarSounds/sound_BombPurrglar_Collect_FlyStart.mp3"
LevelBombPurrglarConfig.Sound_Collect_flyEnd = "BombPurrglarSounds/sound_BombPurrglar_Collect_FlyEnd.mp3"

LevelBombPurrglarConfig.Sound_Bonus1_buling = "BombPurrglarSounds/sound_BombPurrglar_Bonus1_Buling.mp3"
LevelBombPurrglarConfig.Sound_Bonus1_changeWild = "BombPurrglarSounds/sound_BombPurrglar_Bonus1_Changewild.mp3"
LevelBombPurrglarConfig.Sound_Bonus2_buling = "BombPurrglarSounds/sound_BombPurrglar_Bonus2_Buling.mp3"
LevelBombPurrglarConfig.Sound_Bonus2_changeWild = "BombPurrglarSounds/sound_BombPurrglar_Bonus2_Changewild.mp3"
LevelBombPurrglarConfig.Sound_Bonus3_bomb = "BombPurrglarSounds/sound_BombPurrglar_Bonus3_Bomb.mp3"


LevelBombPurrglarConfig.Sound_Multiwild_change = "BombPurrglarSounds/sound_BombPurrglar_Multiwild_Change.mp3"


LevelBombPurrglarConfig.Sound_Scatter_buling = "BombPurrglarSounds/sound_BombPurrglar_Scatter_Buling.mp3"
LevelBombPurrglarConfig.Sound_Scatter_trigger = "BombPurrglarSounds/sound_BombPurrglar_Scatter_Trigger.mp3"

LevelBombPurrglarConfig.Sound_BonusStart = "BombPurrglarSounds/sound_BombPurrglar_BonusStart.mp3"

LevelBombPurrglarConfig.Sound_BonusGuochang_start = "BombPurrglarSounds/sound_BombPurrglar_BonusGuochang_Start.mp3"
LevelBombPurrglarConfig.Sound_BonusDog_closeDoor = "BombPurrglarSounds/sound_BombPurrglar_BonusDog_CloseDoor.mp3"
LevelBombPurrglarConfig.Sound_BonusKey_fly_1 = "BombPurrglarSounds/sound_BombPurrglar_BonusKey_Fly_1.mp3"
LevelBombPurrglarConfig.Sound_BonusKey_fly_2 = "BombPurrglarSounds/sound_BombPurrglar_BonusKey_Fly_2.mp3"

LevelBombPurrglarConfig.Sound_BonusSlide_moveUp = "BombPurrglarSounds/sound_BombPurrglar_BonusSlide_MoveUp.mp3"


LevelBombPurrglarConfig.Sound_BonusPlayerItem_moveUp = "BombPurrglarSounds/sound_BombPurrglar_BonusPlayerItem_MoveUp.mp3"

LevelBombPurrglarConfig.Sound_BonusSymbol_bombAllTip = "BombPurrglarSounds/sound_BombPurrglar_BonusSymbol_BombAllTip.mp3"
LevelBombPurrglarConfig.Sound_BonusCat_bombAll = "BombPurrglarSounds/sound_BombPurrglar_BonusCat_BombAll.mp3"
LevelBombPurrglarConfig.Sound_BonusSymbol_bombAll = "BombPurrglarSounds/sound_BombPurrglar_BonusSymbol_BombAll.mp3"

LevelBombPurrglarConfig.Sound_Bonus_collectMulti = "BombPurrglarSounds/sound_BombPurrglar_Bonus_CollectMulti.mp3"

LevelBombPurrglarConfig.Sound_Bonus_reelMoveDown = "BombPurrglarSounds/sound_BombPurrglar_Bonus_reelMoveDown.mp3"

LevelBombPurrglarConfig.Sound_Bonus_overTip = "BombPurrglarSounds/sound_BombPurrglar_Bonus_OverTip.mp3"

LevelBombPurrglarConfig.Sound_Bonus_getGoldKey = "BombPurrglarSounds/sound_BombPurrglar_Bonus_getGoldKey.mp3"

LevelBombPurrglarConfig.Sound_Bonus_getGoldKey_run = "BombPurrglarSounds/sound_BombPurrglar_Bonus_getGoldKey_run.mp3"

LevelBombPurrglarConfig.Sound_BonusPlayerItem_light = "BombPurrglarSounds/sound_BombPurrglar_BonusPlayerItem_light.mp3"

LevelBombPurrglarConfig.Sound_BonusBox_show = "BombPurrglarSounds/sound_BombPurrglar_BonusBox_Show.mp3"

LevelBombPurrglarConfig.Sound_BonusGoldKey_unlock = "BombPurrglarSounds/sound_BombPurrglar_BonusGoldKey_Unlock.mp3"

LevelBombPurrglarConfig.Sound_BonusBox_multiFly = "BombPurrglarSounds/sound_BombPurrglar_BonusBox_MultiFly.mp3"
LevelBombPurrglarConfig.Sound_BonusBox_multiFly_end = "BombPurrglarSounds/sound_BombPurrglar_BonusBox_MultiFly_End.mp3"

LevelBombPurrglarConfig.Sound_BonusRank_show = "BombPurrglarSounds/sound_BombPurrglar_BonusRank_Show.mp3"
LevelBombPurrglarConfig.Sound_BonusRank_over = "BombPurrglarSounds/sound_BombPurrglar_BonusRank_Over.mp3"

LevelBombPurrglarConfig.Sound_BonusOver_show = "BombPurrglarSounds/sound_BombPurrglar_BonusOver_Show.mp3"
--[[
    
]]
return  LevelBombPurrglarConfig