--[[
]]
GD.CardNoviceCfg = {}

CardNoviceCfg.YEAR = "3023"
CardNoviceCfg.ALBUMID = "302301"
CardNoviceCfg.UNLOCK_LEVEL = 1

-- ViewEventType.CARD_NOVICE_OVER = "CARD_NOVICE_OVER"

CardNoviceCfg.EVENT_NAME = {
    CARD_NOVICE_SALE_BUY_SUCCESS = "CARD_NOVICE_SALE_BUY_SUCCESS", -- 新手期集卡 促销 购买成功
    REMOVE_CARD_NOVICE_DOUBLE_REWARD_HALL_SLIDE = "REMOVE_CARD_NOVICE_DOUBLE_REWARD_HALL_SLIDE", -- 新手期集卡 双倍奖励 结束 移除轮播展示
    REMOVE_CARD_NOVICE_SALE_HALL_SLIDE = "REMOVE_CARD_NOVICE_SALE_HALL_SLIDE", -- 新手期集卡 促销 结束 移除轮播展示
}