--[[
    DiyFeatrue配置
    author:{author}
    time:2023-09-24 14:32:58
]]


_G.DiyFeatureConfig = {}


-- DIYFEATURE首次进入关卡点击
ViewEventType.NOTIFY_ACTIVITY_DIYFEATURE_FIRST_LAYER_CLICK = "NOTIFY_ACTIVITY_DIYFEATURE_FIRST_LAYER_CLICK"
-- DIYFEATURE关闭二次确认弹板
ViewEventType.NOTIFY_ACTIVITY_DIYFEATURE_COLSE_CONFIRM_LAYER = "NOTIFY_ACTIVITY_DIYFEATURE_COLSE_CONFIRM_LAYER"
-- 切换DIYFEATURE开关（on off）
ViewEventType.NOTIFY_ACTIVITY_DIYFEATURE_SWITCH_ONOFF = "NOTIFY_ACTIVITY_DIYFEATURE_SWITCH_ONOFF"
-- DIYFEATURE 飞完积分
ViewEventType.NOTIFY_ACTIVITY_DIYFEATURE_FLYPOINT_OVER = "NOTIFY_ACTIVITY_DIYFEATURE_FLYPOINT_OVER"
-- DIYFEATURE 购买促销成功
ViewEventType.NOTIFY_ACTIVITY_DIYFEATURE_BUYSALE_SUCCESS = "NOTIFY_ACTIVITY_DIYFEATURE_BUYSALE_SUCCESS"
-- DIYFEATURE 气泡相关
ViewEventType.NOTIFY_ACTIVITY_DIYFEATURE_BUFF_BUBBLE = "NOTIFY_ACTIVITY_DIYFEATURE_BUFF_BUBBLE"
-- DIYFEATURE 结束促销付费
ViewEventType.NOTIFY_ACTIVITY_DIYFEATURE_BUYOVERSALE_SUCCESS = "NOTIFY_ACTIVITY_DIYFEATURE_BUYOVERSALE_SUCCESS"
-- DIYFEATURE 刷新左边栏
ViewEventType.NOTIFY_ACTIVITY_DIYFEATURE_REFRESH_ENTRY = "NOTIFY_ACTIVITY_DIYFEATURE_REFRESH_ENTRY"
