--[[
    新版常规促销
--]]
local FirstSaleMultiConfig = {}

ViewEventType.NOTIFY_ROUTINE_SALE_WHEEL_REWARD = "NOTIFY_ROUTINE_SALE_WHEEL_REWARD" -- 轮盘奖励
ViewEventType.NOTIFY_ROUTINE_SALE_BUY_SUCCESS = "NOTIFY_ROUTINE_SALE_BUY_SUCCESS" -- 购买
ViewEventType.NOTIFY_ROUTINE_SALE_BUY_FAILED = "NOTIFY_ROUTINE_SALE_BUY_FAILED" -- 购买
ViewEventType.NOTIFY_ROUTINE_SALE_WHEEL_UPDATE = "NOTIFY_ROUTINE_SALE_WHEEL_UPDATE" -- 更新轮盘数据
ViewEventType.NOTIFY_ROUTINE_SALE_WHEEL_REWARD_CLOSE = "NOTIFY_ROUTINE_SALE_WHEEL_REWARD_CLOSE" -- 奖励界面关闭
ViewEventType.NOTIFY_ROUTINE_SALE_TIME_OUT = "NOTIFY_ROUTINE_SALE_TIME_OUT" -- 时间到

return FirstSaleMultiConfig