-- 新版钻石挑战活动 配置

GD.NewDChallengeConfig = {}

GD.DC_GameType = {
    
}

GD.DC_PickType = {
    Star = "NONE",
    Grand = "GRAND",
    Major = "MAJOR",
    Minor = "MINOR",
    Mini = "MINI",
    AddCoin = "ADD_COINS",
    DelCoin = "REDUCE_COINS",
    MulCoin = "MULTIPLY",
    GameOver = "OVER"
}

ViewEventType.NOTIFY_NDC_TASK_ITEMRESH = "NOTIFY_NDC_TASK_ITEMRESH" --刷新某item
ViewEventType.NOTIFY_NDC_TASK_LISTRESH = "NOTIFY_NDC_TASK_LISTRESH" --刷新任务列表
ViewEventType.NOTIFY_NDC_TASK_CLICKQIPAO = "NOTIFY_NDC_TASK_CLICKQIPAO" --弹出气泡
ViewEventType.NOTIFY_NDC_TASK_REMOVEQIPAO = "NOTIFY_NDC_TASK_REMOVEQIPAO" --删除气泡
ViewEventType.NOTIFY_NDC_TASK_RED = "NOTIFY_NDC_TASK_RED" --刷新任务红点
ViewEventType.NOTIFY_NDC_RUSH_RED = "NOTIFY_NDC_RUSH_RED" --刷新限时红点
ViewEventType.NOTIFY_NDC_MAIN_GUIDE = "NOTIFY_NDC_MAIN_GUIDE" --引导
ViewEventType.NOTIFY_NDC_RUSH_COLLECT = "NOTIFY_NDC_RUSH_COLLECT" --限时活动领奖
ViewEventType.NOTIFY_NDC_COIN_GUESS_REWARD_CLOSE = "NOTIFY_NDC_COIN_GUESS_REWARD_CLOSE"
ViewEventType.NOTIFY_NDC_TASK_ONEITEM = "NOTIFY_NDC_TASK_ONEITEM" --刷新某item
ViewEventType.NOTIFY_NDC_MAIN_CLOSE = "NOTIFY_NDC_MAIN_CLOSE" --关闭主界面
ViewEventType.NOTIFY_NDC_TASK_JCITEM = "NOTIFY_NDC_TASK_JCITEM" --刷新某item
ViewEventType.NOTIFY_NDC_TASK_GUIDE4 = "NOTIFY_NDC_TASK_GUIDE4" --引导第四部
ViewEventType.NOTIFY_NDC_TASK_JCFLY = "NOTIFY_NDC_TASK_JCFLY" --加成
ViewEventType.NOTIFY_NDC_TASK_JCICON = "NOTIFY_NDC_TASK_JCICON" --加成
ViewEventType.NOTIFY_NDC_TASK_ZHUDONG = "NOTIFY_NDC_TASK_ZHUDONG" --主动刷新
ViewEventType.NOTIFY_NDC_TASK_KUATIAN = "NOTIFY_NDC_TASK_KUATIAN" --跨天刷新

ViewEventType.NOTIFY_NDC_REWARD_CLICK_CELL = "NOTIFY_NDC_REWARD_CLICK_CELL" -- pass 点击格子刷新气泡位置
ViewEventType.NOTIFY_NDC_REWARD_TOUCH_TABLE = "NOTIFY_NDC_REWARD_TOUCH_TABLE" -- pass 滑动TableView 点击的那一下
ViewEventType.NOTIFY_NDC_REWARD_MOVED_TABLE = "NOTIFY_NDC_REWARD_MOVED_TABLE" -- pass 滑动TableView

ViewEventType.NOTIFY_NDC_BUY_REFRESH_TICKET = "NOTIFY_NDC_BUY_REFRESH_TICKET" -- 购买刷新券操作完成

ViewEventType.NOTIFY_NDC_EXCHANGE = "NOTIFY_NDC_EXCHANGE" -- 兑换完成
