-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
local bpi = require("protobuf.BaseProtoFunction")
module('ChatBaseProto_pb')


local localTable = {}
localTable.RESPONSECODE = protobuf.EnumDescriptor()
localTable.RESPONSECODE_SUCCEED_ENUM = protobuf.EnumValueDescriptor()
localTable.RESPONSECODE_SYSTEM_ERROR_ENUM = protobuf.EnumValueDescriptor()
localTable.RESPONSECODE_ILLEGAL_ARGUMENT_ENUM = protobuf.EnumValueDescriptor()
localTable.RESPONSECODE_AUTHORIZATION_FAILED_ENUM = protobuf.EnumValueDescriptor()
localTable.RESPONSECODE_SID_ILLEGAL_ENUM = protobuf.EnumValueDescriptor()
localTable.REQUESTTYPE = protobuf.EnumDescriptor()
localTable.REQUESTTYPE_AUTH_ENUM = protobuf.EnumValueDescriptor()
localTable.REQUESTTYPE_SYNC_ENUM = protobuf.EnumValueDescriptor()
localTable.REQUESTTYPE_SEND_ENUM = protobuf.EnumValueDescriptor()
localTable.REQUESTTYPE_HEART_ENUM = protobuf.EnumValueDescriptor()
localTable.REQUESTTYPE_COLLECT_ENUM = protobuf.EnumValueDescriptor()
localTable.REQUESTTYPE_NOTICE_ENUM = protobuf.EnumValueDescriptor()
localTable.REQUESTTYPE_COLLECT_ALL_ENUM = protobuf.EnumValueDescriptor()
RESPONSE = protobuf.Descriptor()
localTable.RESPONSE_CODE_FIELD = protobuf.FieldDescriptor()
localTable.RESPONSE_DESC_FIELD = protobuf.FieldDescriptor()

SUCCEED = 1
SYSTEM_ERROR = 2
ILLEGAL_ARGUMENT = 3
AUTHORIZATION_FAILED = 4
SID_ILLEGAL = 5
AUTH = 1001
SYNC = 1002
SEND = 1003
HEART = 1004
COLLECT = 1005
NOTICE = 1006
COLLECT_ALL = 1007

bpi.setEnumInfo(localTable.RESPONSECODE_SUCCEED_ENUM,"SUCCEED",0,1)
bpi.setEnumInfo(localTable.RESPONSECODE_SYSTEM_ERROR_ENUM,"SYSTEM_ERROR",1,2)
bpi.setEnumInfo(localTable.RESPONSECODE_ILLEGAL_ARGUMENT_ENUM,"ILLEGAL_ARGUMENT",2,3)
bpi.setEnumInfo(localTable.RESPONSECODE_AUTHORIZATION_FAILED_ENUM,"AUTHORIZATION_FAILED",3,4)
bpi.setEnumInfo(localTable.RESPONSECODE_SID_ILLEGAL_ENUM,"SID_ILLEGAL",4,5)
bpi.setEnumValues(localTable.RESPONSECODE,"ResponseCode","chat.ResponseCode",{localTable.RESPONSECODE_SUCCEED_ENUM,localTable.RESPONSECODE_SYSTEM_ERROR_ENUM,localTable.RESPONSECODE_ILLEGAL_ARGUMENT_ENUM,localTable.RESPONSECODE_AUTHORIZATION_FAILED_ENUM,localTable.RESPONSECODE_SID_ILLEGAL_ENUM})
bpi.setEnumInfo(localTable.REQUESTTYPE_AUTH_ENUM,"AUTH",0,1001)
bpi.setEnumInfo(localTable.REQUESTTYPE_SYNC_ENUM,"SYNC",1,1002)
bpi.setEnumInfo(localTable.REQUESTTYPE_SEND_ENUM,"SEND",2,1003)
bpi.setEnumInfo(localTable.REQUESTTYPE_HEART_ENUM,"HEART",3,1004)
bpi.setEnumInfo(localTable.REQUESTTYPE_COLLECT_ENUM,"COLLECT",4,1005)
bpi.setEnumInfo(localTable.REQUESTTYPE_NOTICE_ENUM,"NOTICE",5,1006)
bpi.setEnumInfo(localTable.REQUESTTYPE_COLLECT_ALL_ENUM,"COLLECT_ALL",6,1007)
bpi.setEnumValues(localTable.REQUESTTYPE,"RequestType","chat.RequestType",{localTable.REQUESTTYPE_AUTH_ENUM,localTable.REQUESTTYPE_SYNC_ENUM,localTable.REQUESTTYPE_SEND_ENUM,localTable.REQUESTTYPE_HEART_ENUM,localTable.REQUESTTYPE_COLLECT_ENUM,localTable.REQUESTTYPE_NOTICE_ENUM,localTable.REQUESTTYPE_COLLECT_ALL_ENUM})
bpi.setFieldEnumInfo(localTable.RESPONSE_CODE_FIELD,"code","chat.Response.code",1,0,2,true,SUCCEED,localTable.RESPONSECODE,14,8)
bpi.setFieldBaseInfo(localTable.RESPONSE_DESC_FIELD,"desc","chat.Response.desc",2,1,1,false,"",9,9)
bpi.setMessageInfo(RESPONSE,"Response","chat.Response",{},{},{localTable.RESPONSE_CODE_FIELD, localTable.RESPONSE_DESC_FIELD},false,{})

Response = protobuf.Message(RESPONSE)

