local BindPhoneAreaData = {
    {id = "1", country = "United States of America", code = "1"},
    {id = "2", country = "Germany", code = "49"},
    {id = "3", country = "United Kingdom", code = "44"},
    {id = "4", country = "Australia", code = "61"},
    {id = "5", country = "Canada", code = "1"},
    {id = "6", country = "Albania", code = "355"},
    {id = "7", country = "Andorra", code = "376"},
    {id = "8", country = "Anguilla", code = "1"},
    {id = "9", country = "Antigua and Barbuda", code = "1"},
    {id = "10", country = "Argentina", code = "54"},
    {id = "11", country = "Armenia", code = "374"},
    {id = "12", country = "Aruba", code = "297"},
    {id = "13", country = "Austria", code = "43"},
    {id = "14", country = "Azerbaijan", code = "994"},
    {id = "15", country = "Bahamas", code = "1"},
    {id = "16", country = "Bahrain", code = "973"},
    {id = "17", country = "Bangladesh", code = "880"},
    {id = "18", country = "Barbados", code = "1"},
    {id = "19", country = "Belarus", code = "375"},
    {id = "20", country = "Belgium", code = "32"},
    {id = "21", country = "Bermuda", code = "1"},
    {id = "22", country = "Bolivia", code = "591"},
    {id = "23", country = "Bosnia and Herzegovina", code = "387"},
    {id = "24", country = "Brazil", code = "55"},
    {id = "25", country = "British Virgin Islands", code = "1"},
    {id = "26", country = "Brunei Darussalam", code = "673"},
    {id = "27", country = "Bulgaria", code = "359"},
    {id = "28", country = "Cambodia", code = "855"},
    {id = "29", country = "Chile", code = "56"},
    {id = "30", country = "China", code = "86"},
    {id = "31", country = "Colombia", code = "57"},
    {id = "32", country = "Costa Rica", code = "506"},
    {id = "33", country = "Croatia", code = "385"},
    {id = "34", country = "Curaçao", code = "599"},
    {id = "35", country = "Cyprus", code = "357"},
    {id = "36", country = "Czech Republic", code = "420"},
    {id = "37", country = "Denmark", code = "45"},
    {id = "38", country = "Djibouti", code = "253"},
    {id = "39", country = "Dominican Republic", code = "1"},
    {id = "40", country = "Ecuador", code = "593"},
    {id = "41", country = "Egypt", code = "20"},
    {id = "42", country = "EI Salvador", code = "503"},
    {id = "43", country = "Estonia", code = "372"},
    {id = "44", country = "Finland", code = "358"},
    {id = "45", country = "France", code = "33"},
    {id = "46", country = "French Polynesia", code = "689"},
    {id = "47", country = "Gabon", code = "241"},
    {id = "48", country = "Georgia", code = "995"},
    {id = "49", country = "Greece", code = "30"},
    {id = "50", country = "Guadeloupe", code = "590"},
    {id = "51", country = "Guam", code = "1"},
    {id = "52", country = "Guatemala", code = "502"},
    {id = "53", country = "Guernsey", code = "44"},
    {id = "54", country = "Haiti", code = "509"},
    {id = "55", country = "Hongkong", code = "852"},
    {id = "56", country = "Hungary", code = "36"},
    {id = "57", country = "Iceland", code = "354"},
    {id = "58", country = "India", code = "91"},
    {id = "59", country = "Indonesia", code = "62"},
    {id = "60", country = "Iran", code = "98"},
    {id = "61", country = "Iraq", code = "964"},
    {id = "62", country = "Ireland", code = "353"},
    {id = "63", country = "Israel", code = "972"},
    {id = "64", country = "Italy", code = "39"},
    {id = "65", country = "Jamaica", code = "1"},
    {id = "66", country = "Japan", code = "81"},
    {id = "67", country = "Jordan", code = "962"},
    {id = "68", country = "Kazakhstan", code = "7"},
    {id = "69", country = "Kuwait", code = "965"},
    {id = "70", country = "Laos", code = "856"},
    {id = "71", country = "Latvia", code = "371"},
    {id = "72", country = "Lebanon", code = "961"},
    {id = "73", country = "Libya", code = "218"},
    {id = "74", country = "Lithuania", code = "370"},
    {id = "75", country = "Luxembourg", code = "352"},
    {id = "76", country = "Macao", code = "853"},
    {id = "77", country = "Malaysia", code = "60"},
    {id = "78", country = "Maldives", code = "960"},
    {id = "79", country = "Malta", code = "356"},
    {id = "80", country = "Martinique", code = "596"},
    {id = "81", country = "Mauritius", code = "230"},
    {id = "82", country = "Mexico", code = "52"},
    {id = "83", country = "Moldova, Republic of", code = "373"},
    {id = "84", country = "Morocco", code = "212"},
    {id = "85", country = "Mozambique", code = "258"},
    {id = "86", country = "Myanmar", code = "95"},
    {id = "87", country = "Namibia", code = "264"},
    {id = "88", country = "Nepal", code = "977"},
    {id = "89", country = "Netherlands", code = "31"},
    {id = "90", country = "New Caledonia", code = "687"},
    {id = "91", country = "New Zealand", code = "64"},
    {id = "92", country = "Nicaragua", code = "505"},
    {id = "93", country = "Nigeria", code = "234"},
    {id = "94", country = "North Macedonia", code = "389"},
    {id = "95", country = "Norway", code = "47"},
    {id = "96", country = "Oman", code = "968"},
    {id = "97", country = "Pakistan", code = "92"},
    {id = "98", country = "Panama", code = "507"},
    {id = "99", country = "Paraguay", code = "595"},
    {id = "100", country = "Peru", code = "51"},
    {id = "101", country = "Philippines", code = "63"},
    {id = "102", country = "Poland", code = "48"},
    {id = "103", country = "Portugal", code = "351"},
    {id = "104", country = "Puerto Rico", code = "1"},
    {id = "105", country = "Qatar", code = "974"},
    {id = "106", country = "Republic of Korea", code = "82"},
    {id = "107", country = "Réunion", code = "262"},
    {id = "108", country = "Romania", code = "40"},
    {id = "109", country = "Russia", code = "7"},
    {id = "110", country = "Saudi Arabia", code = "966"},
    {id = "111", country = "Serbia", code = "381"},
    {id = "112", country = "Singapore", code = "65"},
    {id = "113", country = "Slovakia", code = "421"},
    {id = "114", country = "Slovenia", code = "386"},
    {id = "115", country = "South Africa", code = "27"},
    {id = "116", country = "Spain", code = "34"},
    {id = "117", country = "Sri Lanka", code = "94"},
    {id = "118", country = "St.Kitts and Nevis", code = "1"},
    {id = "119", country = "St.Lucia", code = "1"},
    {id = "120", country = "Sweden", code = "46"},
    {id = "121", country = "Switzerland", code = "41"},
    {id = "122", country = "Taiwan", code = "886"},
    {id = "123", country = "Tanzania", code = "255"},
    {id = "124", country = "Thailand", code = "66"},
    {id = "125", country = "Trinidad and Tobago", code = "1"},
    {id = "126", country = "Turkey", code = "90"},
    {id = "127", country = "U.S. Virgin islands", code = "1"},
    {id = "128", country = "Ukraine", code = "380"},
    {id = "129", country = "United Arab Emirates", code = "971"},
    {id = "130", country = "Uruguay", code = "598"},
    {id = "131", country = "Vanuatu", code = "678"},
    {id = "132", country = "Venezuela", code = "58"},
    {id = "133", country = "Vietnam", code = "84"},
    {id = "134", country = "Zambia", code = "260"},
    {id = "135", country = "Zimbabwe", code = "263"},
    {id = "136", country = "Kenya", code = "00254"}
}
return BindPhoneAreaData
