--[[
    @desc: 
    author:JohnnyFred
    time:2021-08-25 11:20:16
]]
local DynamicZOrderConfig = {
    "CardGame_Seeker302301",
    "CardsRes302301",
    "NewUserExpand",
    --头像框资源
    "CommonAvatar",
    "AvatarFrameItem",
    "AvatarFrameSlotSeason7_12",
    "AvatarFrameSlotSeason1_6",
    "AvatarFrame",
    "PaymentConfirmation",
    --高倍场
    "Activity_DeluexeClub_Code",
    "Activity_DeluexeClub",
    --cashBonus
    "cashBonusDy",
    -- 公会
    "Club_res",
    -- 打鸭子
    "Activity_DuckShot",
    "Activity_DuckShot_Code",
    -- 快速点击小游戏
    "Activity_PiggyClicker",
    "Activity_PiggyClickerCode",
    --每日任务+pass
    "Activity_NewPassInbox",
    --集卡
    "CardsBase201902",
    "CardsResInbox",
    "CardPuzzleInbox",
    "CardsMusic",
    "CardsResStatueGame",
    "CardStore",
    "CardObsidian_2",
    "CardObsidian_3",
    "CardGame_Seeker202301",
    "CardSpecialClan_202301",
    "CardsRes202301",
    --比赛
    "Activity_Leagues_CommonRes",
    "Activity_Leagues",
    "Activity_Leagues_qualified",
    "Activity_Leagues_summit",
    --常规Quest
    "Activity_QuestChineseStyleCode",
    "Activity_QuestFairyTalesCode",
    "Activity_QuestPirateCode",
    "Activity_QuestHawaiiCode",
    "Activity_QuestHalloweenCode",
    "Activity_QuestThanksGivingCode",
    "Activity_QuestEasterCode",
    "Activity_QuestChristmasCode",
    "Activity_QuestBase",
    "Activity_QuestNewBase",
    "Activity_QuestPirate",
    "Activity_QuestChineseStyle",
    "Activity_QuestFairyTales",
    "Activity_QuestHawaii",
    "Activity_QuestThanksGiving",
    "Activity_QuestEaster",
    "Activity_QuestHalloween",
    "Activity_QuestChristmas",
    "Activity_QuestInbox",
    --Bingo
    "Activity_BingoTaskCode",
    "Activity_Bingo",
    "Activity_BingoTaskInbox",
    "Activity_BingoInbox",
    --Blast
    "Activity_Blast",
    "Activity_BlastEaster",
    "Activity_BlastHalloween",
    "Activity_BlastThanksGiving",
    "Activity_BlastChristmas",
    "Activity_Blast3RD",
    "Activity_BlastBlossom",
    "Activity_BlastMermaid",
    "Activity_BlastTaskCode",
    "Activity_BlastTaskInbox",
    --推币机
    "Activity_CoinPusherTaskCode",
    "Activity_CoinPusher",
    "Activity_CoinPusher_Easter",
    "Activity_CoinPusherTask",
    "Activity_CoinPusherEasterTask",
    "Activity_CoinPusherTaskInbox",
    --大富翁
    "Activity_RichManTaskCode",
    "Activity_RichMan",
    "Activity_RichManTaskInbox",
    --餐厅
    "Activity_DiningRoomTaskCode",
    "Activity_DiningRoom",
    "Activity_DiningRoomTask",
    "Activity_DiningRoomInbox",
    "Activity_DiningRoomTaskInbox",
    "Activity_DiningRoomFoodInbox",
    --装修
    "Activity_RedecorTaskCode",
    "Activity_Redecor",
    "Activity_RedecorTaskInbox",
    "Activity_RedecorShowTopInbox",
    --word
    "Activity_WordTaskCode",
    "Activity_Word",
    "Activity_WordTaskInBox",
    -- bingo比赛
    "Activity_BingoRushCode",
    "Activity_BingoRush",
    --钻石挑战
    "Activity_LuckyChallengeCode",
    "Activity_LuckyChallenge",
}
return DynamicZOrderConfig
