--[[
    
]]

local MissionsToDIYConfig = {}

ViewEventType.MISSIONS_TO_DIY_COLLECT = "MISSIONS_TO_DIY_COLLECT"
ViewEventType.MISSIONS_TO_DIY_DECORATE_SELECT = "MISSIONS_TO_DIY_DECORATE_SELECT"
ViewEventType.MISSIONS_TO_DIY_REFRESH_DATA = "MISSIONS_TO_DIY_REFRESH_DATA"
ViewEventType.MISSIONS_TO_DIY_UPDATE_DATA = "MISSIONS_TO_DIY_UPDATE_DATA"

return MissionsToDIYConfig