
local DIYFeatureMissionConfig = {}

DIYFeatureMissionConfig.PAGE_TYPE = {
    SIMPLETASK = 1, --简单任务
    HARDTASK = 2, --困难任务
}
-- DIYFeatureMission 活动数据更新
ViewEventType.NOTIFY_ACTIVITY_DIYFEATUREMISSION_DATA_UPDATE = "NOTIFY_ACTIVITY_DIYFEATUREMISSION_DATA_UPDATE"
-- DIYFeatureMission 领取任务奖励
ViewEventType.NOTIFY_ACTIVITY_DIYFEATUREMISSION_TASK_COLLECT = "NOTIFY_ACTIVITY_DIYFEATUREMISSION_TASK_COLLECT"
-- DIYFeatureMission 领取任务奖励完成
ViewEventType.NOTIFY_ACTIVITY_DIYFEATUREMISSION_TASK_COLLECT_END = "NOTIFY_ACTIVITY_DIYFEATUREMISSION_TASK_COLLECT_END"

return DIYFeatureMissionConfig
